base_config: &BASE_CONFIG
    ## SSL parameters
    nettype: 'transformer'
    evaluation_channel_drop: 1
    drop_type : 'zeros'
    grid_type: 'uniform'
    time_axis: True
    max_block : 0.6
    drop_pix: 0.6
    channel_per: 0.6
    channel_drop_per: 0.3

    validation_aug: !!bool False
    max_block_val : 0.2
    drop_pix_val: 0.15
    channel_per_val: 0.5
    channel_drop_per_val: 0.5

    batch_size: 4

    n_variables: 6
    in_token_codim_en: 1
    hidden_token_codim_en: 6
    lifting_token_codim_en: 12
    lifting_token_codim_pred: 12
    out_token_codim_pred:  1

    n_layers_en: 2
    n_heads_en: [2,2]  

    n_layers_dec: 2
    n_heads_dec: [2,2]

    n_layers_pred: 3
    n_heads_pred: [2,2,2]
    
    scalings_pred: [[1,1], [1,1], [1,1]]
    scalings_en: [[1,1], [1,1]]
    scalings_dec: [[1,1],[1,1]]

    n_modes_en:   [[8, 12, 12], [8, 12, 12]]
    n_modes_dec:  [[8, 12, 12], [8, 12, 12]]
    n_modes_pred: [[8, 12, 12], [8, 12, 12], [8, 12, 12]]

    per_channel_attention: !!bool True

    transform_type: 'fft' # might be also spherical harmonics transform or 'sht'
    tno_integral_op: 'fno'

    use_variable_encodings: !!bool True
    n_encoding_channels: 3
    encoding_modes_t: 8
    encoding_modes_x: 12
    encoding_modes_y: 12

    reconstruction: !!bool True
    enable_cls_token: !!bool True

    add_static_feature: !!bool False

    pretrain_ssl : !!bool True #if true we pretrain the model by SSL

    # if True, it will fine tune the encoder during SL
    # otherwise it will freeze the weight of the encoder 
    # which is trained by SSL
    freeze_encoder : !!bool False
    lr: 0.0001
    weight_decay: 0.00001
    scheduler_step: 20
    scheduler_gamma: 0.5
    epochs: 50
    weight_path: '../weights/ssl_weight.pt'

    # Weights and biases
    wandb_log: False
    wandb_name: 'bench_coda_gino'
    wandb_group: 'neuraloperator'
    wandb_project: 'codano'
    wandb_entity: 'm4e7'
    wandb_log_test_interval: 1


codano_gino: &CODANO_GINO
    <<: *BASE_CONFIG
    epochs: 20
    batch_size: 1
    input_mesh_location: "../Data/MP_data/mesh.csv"
    radius: 0.08
    gno_mlp_layers: [6,8]
    grid_size: [251, 42]
    grid_type: 'uniform'
    
    # Note that we can't actually use more than 10 modes 
    # in the first (temporal) dimension as the current DataLoader
    # organizes x/y pairs with a duration of 5 time frames.
    # The models expect they can take at least half as many
    # frequency modes at a time during convolutions.
    n_modes_en:   [[8, 16, 16], [8, 16, 16]]
    n_modes_dec:  [[8, 16, 16], [8, 16, 16]]
    n_modes_pred: [[8, 16, 16], [8, 16, 16], [8, 16, 16]]
    masking_radius: 0.08


fno_gino: &FNO_GINO
    <<: *CODANO_GINO
    nettype: 'simple'
    in_dim: 7
    hidden_dim: 32
    lifting_dim: 64
    projection_dim: 64
    n_modes:       [[180,30], [180,30],[180,30], [180,30]]
    scalings:      [[1,1],[1,1],[1,1], [1,1]]
    n_layers: 4
    out_dim:  7
    grid_size: [251, 42]
    pretrain_ssl : !!bool False
    freeze_encoder : !!bool False
        
    # does not supporting turning on
    var_enco_channels: 0
    enable_cls_token: !!bool False


fno: &FNO
    <<: *FNO_GINO
    n_modes:       [180,30]
    grid_type: 'uniform'
