base_config: &BASE_CONFIG
    ## SSL parameters
    nettype: 'transformer'
    evaluation_channel_drop: 1
    drop_type : 'zeros'
    grid_type: 'uniform'
    time_axis: True
    
    # The masking routine drops pixels in rectangular blocks.
    masking: False
    # Maximum size of one rectangular block (as a ratio of the full frame):
    max_block: 0.25 
    drop_pix: 0.4  # Percentage of pixels (per channel) to be dropped
    channel_per: 0.4 # Number of channels to be augmented
    channel_drop_per: 0.0 # We are not dropping channels for now

    validation_aug: False
    max_block_val : 0.2
    drop_pix_val: 0.15
    channel_per_val: 0.5
    channel_drop_per_val: 0.5

    # batch_size: 1
    # n_variables: 6
    # TODO(mogab): Generalize to handle shared variables.
    # XXX(mogab): This currently assumes no two equations share variables.
    variables_per_equation:
        0: 1  # SWE: depth
        1: 2  # DIFF: activator, inhibitor 
        2: 3  # NS: density, x-velocity, y-velocity

    per_channel_attention: False

    transform_type: 'fft'
    tno_integral_operator: 'fno'

    use_variable_encodings: True
    ### TUNE P1 ###
    n_encoding_channels: 5
    encoding_modes_t: 10
    encoding_modes_x: 20
    encoding_modes_y: 20
    ### TUNE P1 ###

    reconstruction: True
    enable_cls_token: False

    add_static_feature: False

    # If True we first pretrain the model in a self-supervised learning (SSL)
    # scheme where it learns an embedding of input fields to a latent space.
    pretrain_ssl: True

    # If False, it will fine tune the encoder during SL.
    # Otherwise, it will freeze the weights of the encoder trained by SSL.
    freeze_encoder: False
    lr: 0.0001
    weight_decay: 0.00001
    scheduler_step: 20
    scheduler_gamma: 0.5
    # epochs: 500
    weight_path: '../weights/ssl_weight.pt'
    gradient:
      clip: !!bool True
      threshold: 0.1

    # PDEBench datasets:
    shallow_water:
        filepath: "../Data/2D_rdb_NA_NA.h5"
        # 64 x 64 resolution:
        subsampling_rate: 2
        # 25 samples * 5 a/u pairs per sample:
        sample_size: 1
        # The initial condition is not representative of the rest of the sample:
        offset: 1

    diffusion_reaction:
        filepath: "../Data/2D_diff-react_NA_NA.h5"
        # 64 x 64 resolution:
        subsampling_rate: 2
        # 25 samples * 5 a/u pairs per sample:
        sample_size: 1
        # The initial condition is not representative of the rest of the sample:
        offset: 1

    navier_stokes:
        filepaths: [
            # "/mnt/mogab/data/pdebench/2D/NS_incom/ns_incom_inhom_2d_512-90.h5",
            # "/mnt/mogab/data/pdebench/2D/NS_incom/ns_incom_inhom_2d_512-91.h5",
            # "/mnt/mogab/data/pdebench/2D/NS_incom/ns_incom_inhom_2d_512-92.h5",
            # "/mnt/mogab/data/pdebench/2D/NS_incom/ns_incom_inhom_2d_512-93.h5",
            # "/mnt/mogab/data/pdebench/2D/NS_incom/ns_incom_inhom_2d_512-94.h5",
            # "/mnt/mogab/data/pdebench/2D/NS_incom/ns_incom_inhom_2d_512-95.h5",
            # "/mnt/mogab/data/pdebench/2D/NS_incom/ns_incom_inhom_2d_512-96.h5",
            # "/mnt/mogab/data/pdebench/2D/NS_incom/ns_incom_inhom_2d_512-97.h5",
            # "/mnt/mogab/data/pdebench/2D/NS_incom/ns_incom_inhom_2d_512-98.h5",
            "../Data/ns_incom_inhom_2d_512-90.h5",
        ]
        # 64 x 64 resolution:
        subsampling_rate: 8
        # 1 samples * 50 a/u pairs per sample:
        sample_size: 1

    # Weights and biases
    wandb:
        log: False
        name: 'pdebench_coda'
        group: 'neuraloperator'
        project: 'codano-pdebench'
        entity: 'm4e7'
        log_interval: 20


codano_gino: &CODANO_GINO
    <<: *BASE_CONFIG
    epochs: 200
    batch_size: 10
    # input_mesh_location: "../Data/MP_data/mesh.csv"
    radius: 0.08
    gno_mlp_layers: [6, 8]
    grid_size: [251, 42]
    grid_type: 'uniform'
    
    # Note that we can't actually use more than 10 modes 
    # in the first (temporal) dimension as the current DataLoader
    # organizes x/y pairs with a duration of 5 time frames.
    # The models expect they can take at least half as many
    # frequency modes at a time during convolutions.
    encoder:
        input_token_codimension: 1
        ### TUNE P1 ###
        hidden_token_codimension: 10
        lifting_token_codimension: 12
        n_heads: [2, 3, 2]
        n_modes: [[10, 20, 20], [10, 20, 20], [10, 20, 20]]
        ### TUNE P1 ###
        n_layers: 3
        scalings: [[1, 1], [1, 1], [1, 1]]

    decoder:
        # Expected to be equal to encoder.hidden_token_codimension:
        input_token_codimension: 10
        output_token_codimension: 1
        ### TUNE P1 ###
        hidden_token_codimension: 10
        lifting_token_codimension: 12
        n_heads: [2, 3, 2]
        n_modes: [[10, 20, 20], [10, 20, 20], [10, 20, 20]]
        ### TUNE P1 ###
        n_layers: 3
        scalings: [[1, 1], [1, 1], [1, 1]]

    predictor:
        # Expected to be equal to encoder.hidden_token_codimension:
        input_token_codimension: 10
        output_token_codimension:  10
        ### TUNE P1 ###
        hidden_token_codimension: 10
        lifting_token_codimension: 12
        n_heads: [2, 3, 2, 3, 2]
        n_modes: [[10, 20, 20], [10, 20, 20], [10, 20, 20], [10, 20, 20], [10, 20, 20]]
        ### TUNE P1 ###
        n_layers: 5
        scalings: [[1, 1], [1, 1], [1, 1], [1, 1], [1, 1]]

    masking_radius: 0.08


fno_gino: &FNO_GINO
    <<: *CODANO_GINO
    nettype: 'simple'
    in_dim: 7
    hidden_dim: 32
    lifting_dim: 64
    projection_dim: 64
    n_modes:       [[180,30], [180,30],[180,30], [180,30]]
    scalings:      [[1,1],[1,1],[1,1], [1,1]]
    n_layers: 4
    out_dim:  7
    grid_size: [251, 42]
    pretrain_ssl : !!bool False
    freeze_encoder : !!bool False
        
    # does not supporting turning on
    var_enco_channels: 0
    enable_cls_token: !!bool False


fno: &FNO
    <<: *FNO_GINO
    n_modes:       [180,30]
    grid_type: 'uniform'
