base_config: &BASE_CONFIG
    ## SSL parameters
    nettype: 'transformer'
    evaluation_channel_drop: 1
    drop_type : 'zeros'
    grid_type: 'uniform'
    time_axis: True
    max_block : 0.6
    drop_pix: 0.6
    channel_per: 0.6
    channel_drop_per: 0.3

    validation_aug: !!bool False
    max_block_val : 0.2
    drop_pix_val: 0.15
    channel_per_val: 0.5
    channel_drop_per_val: 0.5

    batch_size: 10
    n_variables: 6

    encoder:
        input_token_codimension: 1
        ### TUNE P1 ###
        hidden_token_codimension: 6
        lifting_token_codimension: 12
        n_heads: [2, 2]
        n_modes: [[8, 12, 12], [8, 12, 12]]
        ### TUNE P1 ###
        n_layers: 2
        scalings: [[1, 1], [1, 1]]

    decoder:
        # Expected to be equal to encoder.hidden_token_codimension:
        input_token_codimension: 6
        output_token_codimension: 1
        ### TUNE P1 ###
        hidden_token_codimension: 6
        lifting_token_codimension: 12
        n_heads: [2, 2]
        n_modes: [[8, 12, 12], [8, 12, 12]]
        ### TUNE P1 ###
        n_layers: 2
        scalings: [[1, 1], [1, 1]]

    predictor:
        # Expected to be equal to encoder.hidden_token_codimension:
        input_token_codimension: 6
        output_token_codimension:  1
        ### TUNE P1 ###
        hidden_token_codimension: 6
        lifting_token_codimension: 12
        n_heads: [2, 2, 2]
        n_modes: [[8, 12, 12], [8, 12, 12], [8, 12, 12]]
        ### TUNE P1 ###
        n_layers: 3
        scalings: [[1, 1], [1, 1], [1, 1]]

    per_channel_attention: False

    transform_type: 'fft'
    tno_integral_operator: 'fno'

    use_variable_encodings: True
    ### TUNE P1 ###
    n_encoding_channels: 3
    encoding_modes_t: 8
    encoding_modes_x: 12
    encoding_modes_y: 12
    ### TUNE P1 ###

    reconstruction: True
    enable_cls_token: False

    add_static_feature: False

    # If True we first pretrain the model in a self-supervised learning (SSL)
    # scheme where it learns an embedding of input fields to a latent space.
    pretrain_ssl: True

    # If False, it will fine tune the encoder during SL.
    # Otherwise, it will freeze the weight of the encoder trained by SSL.
    freeze_encoder: False
    lr: 0.0001
    weight_decay: 0.00001
    scheduler_step: 20
    scheduler_gamma: 0.5
    epochs: 50
    weight_path: '../weights/ssl_weight.pt'
    gradient:
      clip: !!bool True
      threshold: 0.1

    filepath_swe: "/mnt/mogab/data/pdebench/2D/shallow-water/2D_rdb_NA_NA.h5"
    filepath_diff: "/mnt/mogab/data/pdebench/2D/diffusion-reaction/2D_diff-react_NA_NA.h5"
    filepaths_ns: [
        "/mnt/mogab/data/pdebench/2D/NS_incom/ns_incom_inhom_2d_512-90.h5",
        # "/mnt/mogab/data/pdebench/2D/NS_incom/ns_incom_inhom_2d_512-91.h5",
        # "/mnt/mogab/data/pdebench/2D/NS_incom/ns_incom_inhom_2d_512-92.h5",
        # "/mnt/mogab/data/pdebench/2D/NS_incom/ns_incom_inhom_2d_512-93.h5",
        # "/mnt/mogab/data/pdebench/2D/NS_incom/ns_incom_inhom_2d_512-94.h5",
    ]

    # Weights and biases
    wandb:
        log: True
        name: 'bench_coda_gino'
        group: 'neuraloperator'
        project: 'codano-pdebench'
        entity: 'm4e7'
        log_interval: 1


codano_gino: &CODANO_GINO
    <<: *BASE_CONFIG
    epochs: 50
    batch_size: 10
    # input_mesh_location: "../Data/MP_data/mesh.csv"
    radius: 0.08
    gno_mlp_layers: [6, 8]
    grid_size: [251, 42]
    grid_type: 'uniform'
    
    # Note that we can't actually use more than 10 modes 
    # in the first (temporal) dimension as the current DataLoader
    # organizes x/y pairs with a duration of 5 time frames.
    # The models expect they can take at least half as many
    # frequency modes at a time during convolutions.
    encoder:
        input_token_codimension: 1
        ### TUNE P1 ###
        hidden_token_codimension: 6
        lifting_token_codimension: 12
        n_heads: [2, 2]
        n_modes: [[8, 16, 16], [8, 16, 16]]
        ### TUNE P1 ###
        n_layers: 2
        scalings: [[1, 1], [1, 1]]

    decoder:
        # Expected to be equal to encoder.hidden_token_codimension:
        input_token_codimension: 6
        output_token_codimension: 1
        ### TUNE P1 ###
        hidden_token_codimension: 6
        lifting_token_codimension: 12
        n_heads: [2, 2]
        n_modes: [[8, 16, 16], [8, 16, 16]]
        ### TUNE P1 ###
        n_layers: 2
        scalings: [[1, 1], [1, 1]]

    predictor:
        # Expected to be equal to encoder.hidden_token_codimension:
        input_token_codimension: 6
        output_token_codimension:  1
        ### TUNE P1 ###
        hidden_token_codimension: 6
        lifting_token_codimension: 12
        n_heads: [2, 2, 2]
        n_modes: [[8, 16, 16], [8, 16, 16], [8, 16, 16]]
        ### TUNE P1 ###
        n_layers: 3
        scalings: [[1, 1], [1, 1], [1, 1]]

    masking_radius: 0.08


fno_gino: &FNO_GINO
    <<: *CODANO_GINO
    nettype: 'simple'
    in_dim: 7
    hidden_dim: 32
    lifting_dim: 64
    projection_dim: 64
    n_modes:       [[180,30], [180,30],[180,30], [180,30]]
    scalings:      [[1,1],[1,1],[1,1], [1,1]]
    n_layers: 4
    out_dim:  7
    grid_size: [251, 42]
    pretrain_ssl : !!bool False
    freeze_encoder : !!bool False
        
    # does not supporting turning on
    var_enco_channels: 0
    enable_cls_token: !!bool False


fno: &FNO
    <<: *FNO_GINO
    n_modes:       [180,30]
    grid_type: 'uniform'
