base_config: &BASE_CONFIG
    ## SSL parameters
    nettype: 'transformer'
    evaluation_channel_drop: 1
    drop_type : 'zeros'
    grid_type: 'uniform'
    max_block : 0.3
    drop_pix: 0.4
    channel_per: 0.5
    channel_drop_per: 0.5

    validation_aug: !!bool False
    max_block_val : 0.3
    drop_pix_val: 0.4
    channel_per_val: 0.3
    channel_drop_per_val: 1.0

    batch_size: 4

    var_num: 5
    in_token_codim_en: 1
    hidden_token_codim_en: 6
    lifting_token_codim_en: 12
    lifting_token_codim_pred: 12
    out_token_codim_pred:  1
    n_layers_en: 2
    n_heads_en:      [2,2]  
    n_layers_dec: 2
    n_heads_dec:      [2,2]
    n_layers_pred: 3
    n_heads_pred:    [2,2,2]
    
    scalings_pred:     [[1,1], [1,1], [1,1]]
    scalings_en:     [[1,1], [1,1],[1,1]]
    scalings_dec:     [[1,1],[1,1]]

    n_modes_en:       [[100,100], [100,100]]
    n_modes_dec:       [[100,100], [100,100]]
    n_modes_pred:       [[100,100], [100,100],[100,100]]

    per_channel_attention: !!bool True
    

    fft_type: 'fft' # might be also spherical harmonics transform or 'sht'
    tno_integral_op: 'fno'

    var_encoding: !!bool True
    var_enco_channels: 3
    reconstruction: !!bool True
    enable_cls_token: !!bool True

    add_static_feature: !!bool False

    pretrain_ssl : !!bool True #if true we pretrain the model by SSL

    # if True, it will fine tune the encoder during SL
    # otherwise it will freeze the weight of the encoder 
    # which is trained by SSL
    freeze_encoder : !!bool False
    lr: 0.03
    weight_decay: 0.0000
    scheduler_step: 50
    scheduler_gamma: 0.8
    epochs: 50
    weight_path: '../weights/ssl_weight.pt'

    # Weights and biases
    wandb_log: True
    wandb_name: 'codano'
    wandb_group: 'neuraloperator'
    wandb_project: 'CoDA-NO'
    wandb_entity: 'ashiq24'
    wandb_log_test_interval: 1

codano_gno: &CODANO_GNO
    <<: *BASE_CONFIG
    epochs: 30
    batch_size: 1
    ntrain: None
    ntest: None
    input_mesh_location: "../Data/MP_data/mesh.csv"
    radius: 0.15
    gno_mlp_layers: [10]
    grid_size: [251, 42]
    grid_type: 'non uniform'
    lr: 0.03
    var_enco_channels: 8
    n_modes_en:       [[180,30], [180,30]]
    n_modes_dec:       [[180,30], [180,30]]
    n_modes_pred:       [[180,30], [180,30]]
    
    scalings_pred:     [[1,1], [1,1]]
    scalings_en:     [[1,1], [1,1]]
    scalings_dec:     [[1,1],[1,1]]
    
    masking_radius: 0.08
    weight_decay: 0.0000
    
    in_token_codim_en: 1
    hidden_token_codim_en: 20
    lifting_token_codim_en: 40
    lifting_token_codim_pred: 40
    out_token_codim_pred:  1
    n_layers_en: 2
    n_heads_en:      [20,20]  
    n_layers_dec: 2
    n_heads_dec:      [5,5]
    n_layers_pred: 2
    n_heads_pred:    [20,20]
    
    pretrain_ssl : !!bool True
    freeze_encoder : !!bool True

codano_test: &CODANO_TEST
    <<: *CODANO_GNO
    epochs: 30
    ntrain: 1
    ntest: 1
    channel_per: -1
    per_channel_attention: !!bool True
    
fno_gno: &FNO_GNO
    <<: *CODANO_GNO
    nettype: 'simple'
    in_dim: 5
    hidden_dim: 128
    lifting_dim: 256
    projection_dim: 256
    n_modes:       [[180,30], [180,30],[180,30], [180,30]]
    scalings:      [[1,1],[1,1],[1,1], [1,1]]
    n_layers: 4
    out_dim:  5
    grid_size: [251, 42]
    pretrain_ssl : !!bool False
    freeze_encoder : !!bool False
    
    
    # does not supporting turning on
    var_enco_channels: 0
    enable_cls_token: !!bool False

fno_test: &FNO_TEST
    <<: *FNO_GNO
    epochs: 5
    ntrain: 1
    ntest: 1
    
fno: &FNO
    <<: *FNO_GNO
    wandb_name: 'fno'
    n_modes:       [180,30]
    grid_type: 'uniform'




