base_config: &BASE_CONFIG
    ## SSL parameters
    nettype: 'transformer'
    evaluation_channel_drop: 1
    drop_type : 'zeros'
    grid_type: 'uniform'
    max_block : 0.6
    drop_pix: 0.6
    channel_per: 0.6
    channel_drop_per: 0.3

    validation_aug: !!bool False
    max_block_val : 0.2
    drop_pix_val: 0.15
    channel_per_val: 0.5
    channel_drop_per_val: 0.5

    batch_size: 4

    var_num: 7
    in_token_codim_en: 1
    hidden_token_codim_en: 6
    lifting_token_codim_en: 12
    lifting_token_codim_pred: 12
    out_token_codim_pred:  1

    n_layers_en: 2
    
    n_heads_en:      [2,2]  

    n_layers_dec: 2
    n_heads_dec:      [2,2]

    n_layers_pred: 3
    n_heads_pred:    [2,2,2]
    
    scalings_pred:     [[1,1], [1,1], [1,1]]
    scalings_en:     [[1,1], [1,1]]
    scalings_dec:     [[1,1],[1,1]]

    n_modes_en:       [[100,100], [100,100]]
    n_modes_dec:       [[100,100], [100,100]]
    n_modes_pred:       [[100,100], [100,100],[100,100]]

    per_channel_attention: !!bool True
    

    fft_type: 'fft' # might be also spherical harmonics transform or 'sht'
    tno_integral_op: 'fno'

    var_encoding: !!bool True
    var_enco_channels: 3
    reconstruction: !!bool True
    enable_cls_token: !!bool True

    add_static_feature: !!bool False

    pretrain_ssl : !!bool True #if true we pretrain the model by SSL

    # if True, it will fine tune the encoder during SL
    # otherwise it will freeze the weight of the encoder 
    # which is trained by SSL
    freeze_encoder : !!bool False
    lr: 0.0001
    weight_decay: 0.00001
    scheduler_step: 20
    scheduler_gamma: 0.5
    epochs: 50
    weight_path: '../weights/ssl_weight.pt'


codano_gino: &CODANO_GINO
    <<: *BASE_CONFIG
    epochs: 20
    batch_size: 1
    input_mesh_location: "../Data/MP_data/mesh.csv"
    radius: 0.08
    gno_mlp_layers: [6,8]
    grid_size: [251, 42]
    grid_type: 'non uniform'
    n_modes_en:       [[180,30], [180,30]]
    n_modes_dec:       [[180,30], [180,30]]
    n_modes_pred:       [[180,30], [180,30],[180,30]]
    masking_radius: 0.08

fno_gino: &FNO_GINO
    <<: *CODANO_GINO
    nettype: 'simple'
    in_dim: 7
    hidden_dim_en: 32
    lifting_dim_en: 64
    lifting_dim_pred: 64
    out_dim:  7
    grid_size: [251, 42]
    pretrain_ssl : !!bool False
    freeze_encoder : !!bool False
    
    
    # does not supporting turning on
    var_enco_channels: 0
    enable_cls_token: !!bool False




